name: Backend CI/CD

on:
  push:
    branches:
      - struktur-test
  pull_request:
    branches:
      - struktur-test

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      # Hvis du har tester, fjern kommentaren under:
      # - name: Run tests
      #   run: npm test
      #   working-directory: backend

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        working-directory: backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_BACKEND_TOKEN }}
        run: railway up --service Bachelor-backend --environment production
