name: Backend CI/CD

on:
  push:
    branches:
      - struktur-test
  pull_request:
    branches:
      - struktur-test

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # Run tests
      - name: Run tests
        run: npm test
        working-directory: backend

      # Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npm install -g railway
          railway up
        working-directory: backend
